name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update theme
        run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.91.2"

      - name: Build
        run: hugo --minify

      - name: Add file to git
        run: git add -A

      - name: Commit
        run: git commit -c user.name='Github Action' -c user.email='nobody@github.com' -m "Build website"

      - id: deploy
        name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          dokku-host: "149.202.86.167"
          app-name: "blog"
          remote-branch: "main"
          git-push-flags: "--force"
